Repository gacheon-sw-academy-2023/Frontier-Client, pull requests merged in 2023-02, with the labels that each got.

#49 [feat] 리스트 드래그 앤 드랍 버그 수정, 리스트 수정 기능 추가
  src/components/Board/AddCard/index.tsx
  src/components/Board/AddCard/styles.ts
  src/components/Board/Card/index.tsx
  src/components/Board/Card/styles.ts
  src/components/Board/CardEditor/index.tsx
  src/components/Board/List/index.tsx
  src/components/Board/List/styles.ts
  src/components/Board/ListEditor/index.tsx
  src/components/Board/ListEditor/styles.ts
  src/pages/Board/index.tsx
Labels: bug, feature, design

#53 [feature]: Home화면 관련 API, MSW 추가
  src/App.tsx
  src/components/BoardCard/index.tsx
  src/components/Navbar/styles.ts
  src/interfaces/workspaceInterface.ts
  src/pages/Home/index.tsx
  src/pages/Home/styles.ts
  src/tests/mocks/datasources/workspace.json
  src/tests/mocks/handlers/index.ts
  src/tests/mocks/handlers/workspaceHanlder.ts
Labels: feature

#54 [개선]: 회원가입 API 수정
  src/components/auth/RegisterForm/index.tsx
  src/queries/useSignUpQuery.ts
  src/tests/mocks/handlers/loginHandler.ts
  src/tests/mocks/handlers/signUpHandler.ts
Labels: feature, page:Register, perf

#59 [perf]: 홈화면 UI 개선
  src/App.tsx
  src/assets/images/Frontier-Logo.png
  src/assets/images/Frontier-Logo2.png
  src/assets/images/user-img.png
  src/components/BoardCard/index.tsx
  src/components/Navbar/index.tsx
  src/components/Navbar/styles.ts
  src/components/Sidebar/index.tsx
  src/components/Sidebar/styles.ts
  src/components/Workspace/Box/index.tsx
  src/components/Workspace/Box/styles.ts
  src/interfaces/boardInterface.ts
  src/interfaces/workspaceInterface.ts
  src/pages/Board/index.tsx
  src/pages/Board/styles.ts
  src/pages/Home/index.tsx
  src/pages/Home/styles.ts
  src/pages/Landing/Header/Header.styles.ts
  src/pages/Landing/Header/index.tsx
  src/tests/mocks/datasources/boardData1.json
  src/tests/mocks/datasources/boardData2.json
  src/tests/mocks/datasources/workspace.json
  src/tests/mocks/handlers/boardHanlder.ts
  src/tests/mocks/handlers/index.ts
  src/tests/mocks/handlers/workspaceHanlder.ts
  src/utils/routes.ts
Labels: feature, design, page:Home, perf

#64 [기능]: 네비게이션바 버튼 기능
  src/components/Navbar/index.tsx
  src/components/Navbar/styles.ts
  src/tests/stories/Navbar/Navbar.stories.tsx
Labels: feature, design

#65 [기능]: MSW 핸들러 및 데이터베이스 작성
  .eslintrc.json
  package.json
  src/App.tsx
  src/mocks/browser.ts
  src/mocks/database/index.ts
  src/mocks/database/samples/boardSample.ts
  src/mocks/database/samples/cardSample.ts
  src/mocks/database/samples/listSample.ts
  src/mocks/database/samples/userSample.ts
  src/mocks/database/samples/workspaceSample.ts
  src/mocks/database/stores/boardStore.ts
  src/mocks/database/stores/cardStore.ts
  src/mocks/database/stores/listStore.ts
  src/mocks/database/stores/userStore.ts
  src/mocks/database/stores/workspaceStore.ts
  src/mocks/handlers/authHandler.ts
  src/mocks/handlers/boardHandler.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/listHandler.ts
  src/mocks/handlers/userHandler.ts
  src/mocks/handlers/workspaceHandler.ts
  src/mocks/server.ts
  src/pages/Landing/index.tsx
  src/queries/useLoginQuery.ts
  src/queries/useSignUpQuery.ts
  src/utils/customAxios.ts
  yarn.lock
Labels: feature, refactor, perf

#68 [기능]: API 호출간 사용되는 인터페이스 및 쿼리 추가작성
  package.json
  src/components/auth/LoginForm/index.tsx
  src/components/auth/RegisterForm/index.tsx
  src/interfaces/authInterface.ts
  src/interfaces/boardInterface.ts
  src/interfaces/cardInterface.ts
  src/interfaces/listInterface.ts
  src/interfaces/userInterface.ts
  src/interfaces/workspaceInterface.ts
  src/mocks/database/samples/userSample.ts
  src/queries/useAuthQuery.ts
  src/queries/useBoardQuery.ts
  src/queries/useListQuery.ts
  src/queries/useLoginQuery.ts
  src/queries/useSignUpQuery.ts
  src/queries/useUserQuery.ts
  src/queries/useWorkspaceQuery.ts
  src/recoil/userAtom.ts
  src/tests/cypress/.placeholder
  src/tests/mocks/browser.ts
  src/tests/mocks/datasources/boardData1.json
  src/tests/mocks/datasources/boardData2.json
  src/tests/mocks/datasources/users.json
  src/tests/mocks/datasources/workspace.json
  src/tests/mocks/handlers/boardHanlder.ts
  src/tests/mocks/handlers/index.ts
  src/tests/mocks/handlers/loginHandler.ts
  src/tests/mocks/handlers/signUpHandler.ts
  src/tests/mocks/server.ts
  src/tests/stories/Navbar/Navbar.stories.tsx
  tailwind.config.cjs
  yarn.lock
Labels: feature, refactor, perf

#71 [Test]: 로그인 화면에 대한 스토리북 작성
  .eslintrc.json
  .storybook/main.cjs
  jest.config.cjs
  src/components/Navbar/Navbar.stories.tsx
  src/components/auth/AuthButton.tsx
  src/components/auth/LoginForm/Login.stories.tsx
  src/components/auth/LoginForm/index.tsx
  src/components/auth/RegisterForm/Register.stories.tsx
  src/components/auth/RegisterForm/index.tsx
  src/tests/jest/Login.test.js
  src/tests/jest/example.txt
  src/tests/jest/test.js
  tsconfig.json
Labels: refactor, test

#72 [feat/workspace] 워크스페이스, 홈페이지 기능 정상화
  .lh/src/utils/routes.ts.json
  src/App.tsx
  src/components/Board/Card/index.tsx
  src/components/Board/CardEditor/index.tsx
  src/components/Board/List/index.tsx
  src/components/BoardBox/index.tsx
  src/components/BoardBox/styles.ts
  src/components/Homepage/Box/index.tsx
  src/components/Homepage/Box/styles.ts
  src/components/Navbar/styles.ts
  src/components/Sidebar/index.tsx
  src/components/Sidebar/styles.ts
  src/components/Workspace/Box/index.tsx
  src/components/Workspace/Box/styles.ts
  src/interfaces/listInterface.ts
  src/pages/Board/index.tsx
  src/pages/Board/styles.ts
  src/pages/Home/index.tsx
  src/pages/Home/styles.ts
  src/pages/Workspace/index.tsx
  src/pages/Workspace/styles.ts
  src/recoil/atom.tsx
  src/utils/routes.ts
Labels: bug, feature, design, page:Home

#74 [기능] 최종 발표 전 정리, readme 업데이트
  .eslintrc.json
  .storybook/main.cjs
  README.md
  environment/.env.development
  package.json
  src/App.tsx
  src/components/Board/AddCard/AddCard.stories.tsx
  src/components/Board/AddList/AddList.stories.tsx
  src/components/Board/ListEditor/ListEditor.stories.tsx
  src/components/CardModal/Content/Description.styles.ts
  src/components/CardModal/Content/Description.tsx
  src/components/CardModal/Content/Labels.styles.ts
  src/components/CardModal/Content/Labels.tsx
  src/components/CardModal/Content/Members.styles.ts
  src/components/CardModal/Content/Members.tsx
  src/components/CardModal/Content/index.tsx
  src/components/CardModal/Content/styles.ts
  src/components/CardModal/Header/Header.styles.ts
  src/components/CardModal/Header/index.tsx
  src/components/CardModal/Sidebar/Sidebar.styles.ts
  src/components/CardModal/Sidebar/index.tsx
  src/components/CardModal/index.tsx
  src/components/CardModal/styles.ts
  src/pages/Error/Error.stories.tsx
  src/pages/Error/Error.styles.ts
  src/pages/Error/index.tsx
  src/pages/Landing/Feature/Feature.stories.tsx
  src/pages/Landing/Feature/Feature.styles.ts
  src/pages/Landing/Feature/index.tsx
  src/pages/Landing/Footer/Footer.stories.tsx
  src/pages/Landing/Footer/Footer.styles.ts
  src/pages/Landing/Footer/index.tsx
  src/pages/Landing/Header/Header.interfaces.ts
  src/pages/Landing/Header/Header.stories.tsx
  src/pages/Landing/Header/Header.styles.ts
  src/pages/Landing/Header/index.tsx
  src/pages/Landing/Hero/Hero.interfaces.ts
  src/pages/Landing/Hero/Hero.stories.tsx
  src/pages/Landing/Hero/Hero.styles.ts
  src/pages/Landing/Hero/index.tsx
  src/pages/Landing/Pricing/Pricing.stories.tsx
  src/pages/Landing/Pricing/Pricing.styles.ts
  src/pages/Landing/Pricing/index.tsx
  src/pages/Landing/index.tsx
  src/pages/Login/index.tsx
  src/pages/SignUp/index.tsx
  src/utils/customAxios.ts
  src/utils/routes.ts
  yarn.lock
Labels: feature, design, refactor, perf, test
