Repository gacheon-sw-academy-2023/Frontier-Client, pull requests merged in 2023-01, with the labels that each got.

#7 chore(main): release 1.0.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#20 [feat] 로그인 페이지 기능 구현, yarn 설정 변경
  .yarnrc.yml
  package.json
  src/App.tsx
  src/components/LoginForm/index.tsx
  src/components/LoginForm/styles.ts
  src/components/RegisterForm/index.tsx
  src/components/RegisterForm/styles.ts
  src/interfaces/.placeholder
  src/interfaces/userInterface.ts
  src/pages/Login/index.tsx
  src/pages/Login/styles.ts
  src/pages/SignUp/index.tsx
  src/pages/SignUp/styles.ts
  src/tests/mocks/datasources/.placeholder
  src/tests/mocks/datasources/users.json
  src/tests/mocks/handlers.ts
  src/tests/mocks/handlers/loginHandler.ts
  src/tests/mocks/server.ts
  src/utils/error-message.ts
  src/utils/routes.ts
  src/utils/validation.ts
  yarn.lock
Labels: feature, design

#25 feat: 회원가입 API 작성, 유효성 검사 구현
  src/components/RegisterForm/index.tsx
  src/interfaces/userInterface.ts
  src/tests/mocks/handlers/loginHandler.ts
  src/utils/error-message.ts
Labels: feature, design

#40 [design]랜딩 페이지 내부 헤더
  package.json
  postcss.config.cjs
  src/index.css
  src/pages/Landing/Header/Header.interfaces.ts
  src/pages/Landing/Header/Header.styles.ts
  src/pages/Landing/Header/index.tsx
  src/pages/Landing/LandingContent.cy.tsx
  src/pages/Landing/LandingContent.tsx
  src/pages/Landing/index.tsx
  src/tests/jest/example.test.tsx
  src/tests/stories/Landing/LandingContent.stories.tsx
Labels: feature, design, page:Landing

#44 [perf]: 로그인 페이지 - 로그인 상태 저장, API 개선
  .commitlintrc.json
  .eslintrc.json
  src/App.tsx
  src/apis/apiClient.ts
  src/components/BoardCard/index.tsx
  src/components/LoginForm/index.tsx
  src/components/LoginForm/styles.ts
  src/components/RegisterForm/styles.ts
  src/components/Sidebar/index.tsx
  src/interfaces/userInterface.ts
  src/pages/Home/index.tsx
  src/pages/Home/styles.tsx
  src/pages/Landing/Header/Header.styles.ts
  src/pages/Landing/Header/index.tsx
  src/pages/Landing/Hero/Hero.styles.ts
  src/pages/Landing/Hero/index.tsx
  src/pages/Landing/index.tsx
  src/pages/Login/index.tsx
  src/pages/SignUp/index.tsx
  src/queries/useLoginQuery.ts
  src/recoil/userAtom.ts
  src/tests/jest/.placeholder
  src/tests/mocks/datasources/users.json
  src/tests/mocks/handlers.ts
  src/tests/mocks/handlers/index.ts
  src/tests/mocks/handlers/loginHandler.ts
  src/tests/mocks/handlers/signUpHandler.ts
  src/tests/mocks/handlers/testHandler.ts
  src/tests/stories/.placeholder
  src/utils/.placeholder
  src/utils/sleep.ts
Labels: feature, page:Login, refactor, perf
